spring:
  application:
    name: libraryapi
#  profiles:
#    active: production
#  SPRING_PROFILES_ACTIVE=production
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/library}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

springdoc:
  override-with-generic-response: false # desabilita respostas genericas (Nessa api, respostas de erro padronizadas do ExceptionHandler)

logging:
  pattern:
    console: '%clr(%d{dd/MM/yyyy HH:mm:ss}){blue} %clr(%5p) %clr([%t]){yellow} %clr(%-40.40logger){faint} %clr(:){yellow} %m%n'
  file:
    name:
      libraryapi.log
  level:
    root: warn
    com:
      github:
        IsaacMartins: trace
    org:
      springframework:
        web: debug
        security: trace

# log levels (orderm crescente - do menor pro maior nível):
# trace -> nivel mais detalhado; Rastreio minucioso.
# debug -> informações de depuração (debug).
# info -> informações sobre funcionamento geral da aplicação.
# warn -> eventos potencialmente problemáticos.
# error -> erros
# hierárquico - habilitar 1 level irá habilitar todos os outros levels de nível superior junto ao habilitado.

management: # keyword para configurar endpoints do actuator
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

# production profile
---

spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false

# test profile
---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    show-sql: false